### ISSUE TITLE
Anaconda 

### ISSUE THREAD

**Issue by hichemfelouat** [ai-forever/ghost#60]
I have tried to use sberswap on anaconda with gpu and I found this issue! any suggestion?

Traceback (most recent call last):
  File "inference.py", line 8, in <module>
    from utils.inference.image_processing import crop_face, get_final_image
  File "/content/sber-swap/utils/inference/image_processing.py", line 10, in <module>
    from insightface.utils import face_align
  File "/usr/local/lib/python3.8/site-packages/insightface/__init__.py", line 8, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py", line 9, in <module>
    import onnxruntime.capi._ld_preload  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcublas = CDLL("libcublas.so.10", mode=RTLD_GLOBAL)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.10: cannot open shared object file: No such file or directory

**Comment by RijulGupta-DM** [comment]
The version of pytorch and torchvision used in the requirements.txt file are built for Cuda 10. Your machine doesn't have this version of Cuda installed (it's probably using 11.*). Either upgrade the packages to those which match your version of Cuda or downgrade your version of Cuda to 10.*

**Comment by AlexanderGroshev** [comment]
You need to match the versions of pytorch, mxnet and onnxruntime-gpu to your CUDA. If you are using CUDA 10, you can follow requirements.txt. 
For CUDA 11.2 you can try the following versions:
onnxruntime-gpu==1.8.0
mxnet-cu112==1.9.1
